### ISSUE TITLE
Etcher won't flash the image

### ISSUE THREAD

**Issue by boca812** [Halcy0nic/SUBZero#2]
I have even updated etcher to the latest version 1.4.9
When I selecting the image for flashing, I get a message about "invalid image"

**Comment by F1l3N0tF0und** [comment]
did you open up the tar.bz2 file in winrar and extracted the .img file from it ?

**Comment by Halcy0nic** [comment]
Correct, you have to extract the .img file from the tar.bz2 and use the .img to flash the device.
