### ISSUE TITLE
Trouble Routing

### ISSUE THREAD

**Issue by KnowedUsername** [Halcy0nic/SUBZero#3]
Im having trouble routing the subzero i followed all the steps

**Comment by Halcy0nic** [comment]
Hey @jayvdveen, are you still running into issues after the most recent updates?

**Comment by KnowedUsername** [comment]
Kinda hard to update when I have no connection so I need to take all the files of it and then redo all of it :(

**Comment by KnowedUsername** [comment]
> Hey @jayvdveen, are you still running into issues after the most recent updates?

I reinstalled the whole image file and even did it manually but now the subzero network doesnt even show up any idea why?

**Comment by NickEngmann** [comment]
That was an issue with Issue #9 however that has been resolved so I'm going to close this issue now
