### ISSUE TITLE
Network not broadcast

### ISSUE THREAD

**Issue by cerialphreak** [Halcy0nic/SUBZero#9]
I've built SUBZero from source as well as the img file and either way the wireless network is not broadcast. I've tried configuring the wireless network on the client devices manually in case it was hidden but they still could not find it.

**Comment by NickEngmann** [comment]
can you try building it from source and let us know if you are still having the issue?

**Comment by cerialphreak** [comment]
Just built from scratch again from source (with latest raspbian) and no change. Is there any specific logs I can check to make sure it installed correctly or to see why the AP isn't getting created?

**Comment by NickEngmann** [comment]
Looks like this issue was brought about due to some package upgrades. Going to go ahead and make a branch and implement a fix
